### PR TITLE
.github/pr-golanglint.yaml: Add Golong lint for CI

### PR DESCRIPTION
**Pull request by hwang37**
Add Golong lint for CI.
For #24

### CODE REVIEW

**Comment by dongx1x** [comment]
@hwang37 please check the errors: https://github.com/intel/confidential-cloud-native-primitives/actions/runs/5420595478/jobs/9854943471
Looks like the usage is not correct.

**Comment by hwang37** [comment]
Please don't merge this PR until there're .go files submitted and merged in project first.

**Comment by hwang37** [comment]
We can wait for this PR merge till there's Golong source code in Repo.
(Need to revise the folder path)

**Review by Ruoyu-y — APPROVED** [review]
LGTM

**Pull request merged**
