### PR TITLE
.github/pr-pylint.yaml: Add Python scan in Github action CI.

### PR DESCRIPTION
**Pull request by hwang37**
Add Python scan in Github action CI, for #25

### CODE REVIEW

**Comment by hwang37** [comment]
We can wait for this PR merge till there's Python source code in Repo

**Comment by hwang37** [comment]
Python folder path has been decided and updated in this PR.
Looking for approvers to review and approve.

**Review by Ruoyu-y — APPROVED** [review]
LGTM

**Comment by hwang37** [comment]
Close #25

**Pull request merged**
