### PR TITLE
service/measurement-server: add skeleton for measurement-server service

### LINKED ISSUE #15: Service: design measurement-server to get measurement
Service: design measurement-server to get measurement

### PR DESCRIPTION
**Pull request by Ruoyu-y**
create the base architecture for measurement-server service:
- add go.mod and go.sum file
- add makefile for service
- add basic grpc server logic for the service

resolves #15

### CODE REVIEW

**Comment by hwang37** [comment]
After submitting PR, could you please also update "Reviewers" and "Label" in the webpage?

**Comment by Ruoyu-y** [comment]
> After submitting PR, could you please also update "Reviewers" and "Label" in the webpage?

Sure. Just want to make sure the pr has passed all checks. Then i will add all the reviewers for review.

**Comment by Ruoyu-y** [comment]
Need rebase after #38 merged

**Review by kenplusplus — APPROVED** [review]
LGTM

**Pull request merged**
