### PR TITLE
CI/CD: add action for container build

### LINKED ISSUE #36: Add github action for container build check

### PR DESCRIPTION
**Pull request by Ruoyu-y**
* add action for container build
* rename and add path filter for python license check

resolves #36

### CODE REVIEW

**Comment by hwang37** [comment]
LGTM

**Comment by Ruoyu-y** [comment]
> A minor comment: Next time, suggest split PR into different PRs if it covers multiple, different & independent feature or bug fixing. One PR is to complete one task.

Got it.

**Comment by hwang37** [comment]
LGTM

**Review by hwang37 — APPROVED** [review]
LGTM

**Pull request merged**
